### ISSUE TITLE
Flex布局下设置每个item的width不生效

### ISSUE THREAD

**Issue by AILINGANGEL** [AILINGANGEL/css#11]
1. 问题描述
如果用width指定flex-item的宽度，当其中一个的宽度不够的时候，会挤压相邻的两个flex-item，如下图所示
![image](https://user-images.githubusercontent.com/28471649/60887548-47c6b400-a287-11e9-97cd-a5e5a76d04de.png)

```html
<div class="row">
  <div class="div1">div1div</div>
  <div class="div2">div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2div2divaaaaaaaaza</div>
  <div class="div3">div3</div>
</div>
```

```css
.row {
  display: flex;
  justify-content: space-between;
}

.div1 {
  background-color: red;
  width: 100px;
/*   flex-basis: 100px;
  flex-grow: 0;
  flex-shrink: 0; */
}

.div2 {
  background-color: green;
/*   word-break: break-all; */
}

.div3 {
  background-color: blue;
  width: 100px;
/*   flex-basis: 100px;
  flex-shrink: 0; */
}
```

2. 解决方案

```css
.div1 {
    flex-basis: 100px;
    flex-grow: 0;
    flex-shrink: 0;
}
```

3. 参考stackoverflow [查看](https://stackoverflow.com/questions/21406397/width-ignored-on-flexbox-items)
