### ISSUE TITLE
Chrome下字体10px不生效的问题

### ISSUE THREAD

**Issue by AILINGANGEL** [AILINGANGEL/css#14]
### 问题描述
今天遇到给icon设置大小font-size:10px;但是chrome现实最终为12px;
![image](https://user-images.githubusercontent.com/28471649/61610917-0d004b00-ac8d-11e9-994a-18e0a2e3feca.png)

### 解决方案
```css
 .test {
    -webkit-transform-origin-x: 0;
    transform-origin-x: 0;
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
    font-size: 10px;
}
```

### 参考资料
[chrome浏览器最小字号解决方案](https://juejin.im/post/5a30ebc2f265da4307034318#heading-3)
