### ISSUE TITLE
选择以el-开头的class的元素但不是.el-xx也不是.el-yy的元素

### ISSUE THREAD

**Issue by AILINGANGEL** [AILINGANGEL/css#16]
将以el-开头的类但不是.el-card也不是.el-table的元素的右边距设置成24px;
```css
 [class*='el-']:not(.el-card):not(.el-table) {
        margin-right: 24px;
}
```

下列的代码没有被很好的支持，不推荐使用
```css
 [class*='el-']:not(.el-card, .el-table) {
        margin-right: 24px;
}
```
