### ISSUE TITLE
CSS其他

### ISSUE THREAD

**Issue by AILINGANGEL** [AILINGANGEL/css#5]
## 1.用css画一个三角形

```html
<div class="div1"></div>
```
- 第一步: 设置边框和width,height为0
```css
.div1 {
  width: 0;
  height: 0;
  border-right: 100px solid red;
  border-left: 100px solid green;
  border-top: 100px solid blue;
  border-bottom: 100px solid pink;
}
```
![image](https://user-images.githubusercontent.com/28471649/58612699-14872180-82e6-11e9-8c1d-895160be5a44.png)

- 第二步: 通过控制上下左右的border来控制想要的三角形

```css
.div1 {
  width: 0;
  height: 0;
  border-right: 100px solid transparent;
  border-left: 0px solid transparent;
  border-top: 100px solid blue;
  border-bottom: 0px solid pink;
}
```
![image](https://user-images.githubusercontent.com/28471649/58612817-75165e80-82e6-11e9-899b-cdbde0fa9a9c.png)
