### ISSUE TITLE
CSS三栏布局

### ISSUE THREAD

**Issue by AILINGANGEL** [AILINGANGEL/css#8]
### 方法一: float
```html
<div class="div1"></div>
<div class="center"></div>
<div class="div2"></div>
```

```css
.div1, .div2 {
  width: 200px;
  height: 200px;
  background-color: red;
}

.div1 {
  float: left;
}

.div2 {
  float: right;
}

.center {
  background-color: black;
  float: left;
  width: calc(100% - 400px);
  height: 200px;
}
```

### 方法二: flex
```css

body {
  display: flex;
}
div {
  display: inline-block;
  height: 200px;
}

.div1 {
  width: 200px;
  background-color: red;
}
.div2 {
  width: 200px;
  background-color: red;
}

.center {
   background-color: black;
  flex-grow: 1;
}
```
